# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Focus' Tech Blog
email: ford153focus@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  no desc this time
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://ford153focus.github.io" # the base hostname & protocol for your site
twitter_username: ford153focus
github_username:  ford153focus

# Build settings
markdown: kramdown

exclude: [vendor]

sass:
    sass_dir: _sass